#ifndef StepperMotorFraschetta_h
#define StepperMotorFraschetta_h
#include <BasicStepperMotorFraschetta.h>
class MOTORE_STEPPER:public MOTORE_STEPPER_BASE{
protected:
 uint8_t PIN_CONTROLLO_PASSO,PIN_VERSO;
 boolean STATO_PIN_VERSO_DESTRA;
 void PASSO(){
  digitalWrite(PIN_CONTROLLO_PASSO,HIGH);
  delay(2);
  digitalWrite(PIN_CONTROLLO_PASSO,LOW);
 }
public:
 void PASSO_A_SINISTRA()override{digitalWrite(PIN_VERSO,STATO_PIN_VERSO_DESTRA); PASSO(); MEMORIZZA_PASSI(POSIZIONE()-1);}
 void PASSO_A_DESTRA()override{digitalWrite(PIN_VERSO,!STATO_PIN_VERSO_DESTRA); PASSO(); MEMORIZZA_PASSI(POSIZIONE()+1);}
 MOTORE_STEPPER(uint8_t PIN_CONTROLLO_PASSO,uint8_t PIN_VERSO, boolean STATO_PIN_VERSO_DESTRA, uint16_t PASSI_MASSIMI,uint16_t PERIODO_SPOSTAMENTO_IN_MILLISECONDI):
  MOTORE_STEPPER_BASE(PASSI_MASSIMI,PERIODO_SPOSTAMENTO_IN_MILLISECONDI,PIN_CONTROLLO_PASSO,PIN_VERSO){
   this->PIN_CONTROLLO_PASSO=PIN_CONTROLLO_PASSO;
   this->PIN_VERSO=PIN_VERSO;
   pinMode(PIN_CONTROLLO_PASSO,OUTPUT);
   pinMode(PIN_VERSO,OUTPUT);
  }
};
#endif
