#ifndef BasicEntranceStepperFraschetta_h
#define BasicEntranceStepperFraschetta_h
#include <BasicStepperMotorFraschetta.h>
#include <MotorizedEntranceFraschetta.h>
class STEPPER_INGRESSO_BASE:MOTORE_STEPPER_BASE,public INGRESSO_MOTORIZZATO{
 public:
  virtual uint16_t POSIZIONE()=0;
  void APRI() override {
   MEMORIZZA_STATO(APERTURA);
   MOTORE_STEPPER_BASE::POSIZIONE(FINECORSA_APERTURA);
  }
  void CHIUDI() override {
   MEMORIZZA_STATO(CHIUSURA);
   MOTORE_STEPPER_BASE::POSIZIONE(FINECORSA_CHIUSURA);
  }
  boolean APERTO() override {return POSIZIONE()==FINECORSA_APERTURA;}
  boolean CHIUSO() override {return POSIZIONE()==FINECORSA_CHIUSURA;}
  STEPPER_INGRESSO_BASE(uint16_t PASSI_MASSIMI,uint16_t PASSI_APERTURA,uint16_t PASSI_CHIUSURA,
  uint16_t PERIODO_SPOSTAMENTO_IN_MILLISECONDI,uint16_t INDIRIZZO_EEPROM_CELLA1_POSIZIONE,uint16_t INDIRIZZO_EEPROM_CELLA2_POSIZIONE,uint16_t INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO):
   MOTORE_STEPPER_BASE(PASSI_MASSIMI,PERIODO_SPOSTAMENTO_IN_MILLISECONDI,INDIRIZZO_EEPROM_CELLA1_POSIZIONE,INDIRIZZO_EEPROM_CELLA2_POSIZIONE),
   INGRESSO_MOTORIZZATO(PASSI_APERTURA,PASSI_CHIUSURA,INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO){}
};
#endif
