#include "ArduinoKitFraschetta.h"
SERVOMOTORE S(2);
void setup(){}
void loop(){S.SWIPING(180,0,10,3,SECONDI);}
/*GLI SPASMI INIZIALI NON DIPENDONO DAl CODICE
SE ANCHE STACCANDO IL CAVO DATI DEL SERVOMOTORE
SI VERIFICA UNO SPASMO*/