#ifndef BipolarEntranceStepperFraschetta_h
#define BipolarEntranceStepperFraschetta_h
#include <BipolarStepperMotorFraschetta.h>
#include <BasicEntranceStepperFraschetta.h>
class STEPPER_INGRESSO_BIPOLARE:public MOTORE_STEPPER_BIPOLARE,public STEPPER_INGRESSO_BASE{
 public:
  void CONTROLLO_STATO_MOVIMENTO(){STEPPER_INGRESSO_BASE::CONTROLLO_STATO_MOVIMENTO();}
   uint16_t POSIZIONE() override {return MOTORE_STEPPER_BIPOLARE::POSIZIONE();}
    STEPPER_INGRESSO_BIPOLARE(uint16_t PASSI_MASSIMI,uint8_t PIN_A,uint8_t PIN_B,uint8_t PIN_C,uint8_t PIN_D,
   uint16_t PASSI_APERTURA,uint16_t PASSI_CHIUSURA,uint8_t PERIODO_SPOSTAMENTO_IN_MILLISECONDI):
    MOTORE_STEPPER_BIPOLARE(PASSI_MASSIMI,PERIODO_SPOSTAMENTO_IN_MILLISECONDI,PIN_A,PIN_B,PIN_C,PIN_D),
   STEPPER_INGRESSO_BASE(PASSI_MASSIMI,PASSI_APERTURA,PASSI_CHIUSURA,PERIODO_SPOSTAMENTO_IN_MILLISECONDI,PIN_A,PIN_B,PIN_C){}
};
#endif
