#ifndef TwoStageThermostatFraschetta_h
#define TwoStageThermostatFraschetta_h
#include <ThermostatFraschetta.h>
class TwoStageThermostat{
 protected:
    Thermostat TERM_RISC,TERM_RAFF;
 public:
  TwoStageThermostat(uint8_t PIN_RISCALDAMENTO,uint8_t PIN_RAFFREDDAMENTO,TIPO_DIGITALE TIPORELE){
   TERM_RISC = TERMOSTATO(PIN_RISCALDAMENTO,TIPORELE,RISCALDAMENTO);
   TERM_RAFF = TERMOSTATO(PIN_RAFFREDDAMENTO,TIPORELE,RAFFREDDAMENTO);
  }
  TwoStageThermostat(uint8_t PIN_RISCALDAMENTO,uint8_t PIN_RAFFREDDAMENTO,TIPO_DIGITALE TIPORELE_RISCALDAMENTO,TIPO_DIGITALE TIPORELE_RAFFREDDAMENTO){
   TERM_RISC = TERMOSTATO(PIN_RISCALDAMENTO,TIPORELE_RISCALDAMENTO,RISCALDAMENTO);
   TERM_RAFF = TERMOSTATO(PIN_RAFFREDDAMENTO,TIPORELE_RAFFREDDAMENTO,RAFFREDDAMENTO);
  }
  void FUNZIONE_TERMOSTATO(uint8_t TEMPERATURA_ATTUALE){
   TERM_RISC.FUNZIONE_TERMOSTATO(TEMPERATURA_ATTUALE);
   TERM_RAFF.FUNZIONE_TERMOSTATO(TEMPERATURA_ATTUALE);
  }
  void IMPOSTA_SOGLIA_TEMPERATURA(uint8_t TEMPERATURA){
   TERM_RISC.SOGLIA_TEMPERATURA = TEMPERATURA;
   TERM_RISC.SOGLIA_TEMPERATURA = TEMPERATURA;
  }
  uint8_t SOGLIA_TEMPERATURA(){return TERM_RISC.SOGLIA_TEMPERATURA;}
};
#endif
