#ifndef MotorizedEntranceFraschetta_h
#define MotorizedEntranceFraschetta_h
enum STATO_DEL_MOVIMENTO:uint8_t{CHIUSURA=0,APERTURA=1};
class INGRESSO_MOTORIZZATO{
 protected:
  uint16_t FINECORSA_APERTURA,FINECORSA_CHIUSURA,INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO;
 public:
  virtual void APRI()=0;
  virtual void CHIUDI()=0;
  virtual boolean APERTO()=0;
  virtual boolean CHIUSO()=0;
  void MEMORIZZA_STATO(STATO_DEL_MOVIMENTO STATO){
   EEPROM.update(INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO,STATO);
  }
  void CONTROLLO_STATO_MOVIMENTO(){
   if(EEPROM.read(INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO)){APRI();}
   else{CHIUDI();}
  }
  INGRESSO_MOTORIZZATO(uint16_t FINECORSA_APERTURA,uint16_t FINECORSA_CHIUSURA,uint16_t INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO){
   this->INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO=INDIRIZZO_POSIZIONE_STATO_DEL_MOVIMENTO;
   this->FINECORSA_APERTURA = FINECORSA_APERTURA;
   this->FINECORSA_CHIUSURA = FINECORSA_CHIUSURA;
  }
};
#endif
