#include "ArduinoKitFraschetta.h"
MOTORE_STEPPER_BIPOLARE M(2,3,4,5,512,0);
DEFAULT_SERIAL S(9600);
void setup(){



}
void loop(){
delay(1000);
M.POSIZIONE(511);
S.INVIA_ANDANDO_A_CAPO(M.POSIZIONE());
delay(1000);
M.POSIZIONE(10);
S.INVIA_ANDANDO_A_CAPO(M.POSIZIONE());
}
