#ifndef PhotoresistorFraschetta_h
#define PhotoresistorFraschetta_h
#include <InputFraschetta.h>
#include <VirtualCycleFraschetta.h>
class FOTORESISTORE:ENTRATA,CicloVirtualeF{
protected:
 uint16_t SOGLIA_ACCENSIONE,SOGLIA_SPEGNIMENTO;
 boolean ULTIMO_CONTROLLO_ESEGUITO;
public:
 FOTORESISTORE(uint8_t PIN,uint16_t SOGLIA_ACCENSIONE,uint16_t SOGLIA_SPEGNIMENTO,uint64_t RITARDO,UNITA_DI_TEMPO UNITA):ENTRATA(PIN),CicloVirtualeF(RITARDO,UNITA){
  this->SOGLIA_ACCENSIONE = SOGLIA_ACCENSIONE;
  this->SOGLIA_SPEGNIMENTO = SOGLIA_SPEGNIMENTO;
 }
 uint16_t LEGGI_FOTORESISTORE(){return LETTURA_ANALOGICA();}
 boolean CONTROLLO(){
 if(TICK()){
  if(LEGGI_FOTORESISTORE()>=SOGLIA_ACCENSIONE){ULTIMO_CONTROLLO_ESEGUITO=1; return 1;}
  if(LEGGI_FOTORESISTORE()<=SOGLIA_ACCENSIONE && LEGGI_FOTORESISTORE()>=SOGLIA_SPEGNIMENTO){ return ULTIMO_CONTROLLO_ESEGUITO;}
  ULTIMO_CONTROLLO_ESEGUITO=0; return 0;
 }
 return ULTIMO_CONTROLLO_ESEGUITO;
 }
};
#endif
